name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pyproject.toml'
  
jobs:
            
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
          architecture: 'x64'
          cache: 'pip'
    
      - name: Install pypa/build
        run: python3 -m pip install build --user

      - name: Build binary wheel and source tarball
        run: python3 -m build

      - name: Store the packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/loldeps
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Download dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
    
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1